### ISSUE TITLE
results processing error

### ISSUE THREAD

**Issue by ad2n15** [MRCIEU/PHESANT#10]
Hi,

I am so happy with your tool, but I got an error in running results processing step,

[1] "Finished flow counts"
[1] "Finished combining results"
Error in strsplit(resultsAll$varName, "[-#]", perl = TRUE) :
  non-character argument
Calls: addVariableDescriptions -> sapply -> lapply -> strsplit
Execution halted

This is my code, and I run 100 parallel process:
module load R/3.5.1
cd resultsProcessing/
Rscript mainCombineResults.r \
--resDir=results \
--variablelistfile="../variable-info/outcome-info.tsv" \
--numParts=100

How can I fix this?

Kind Reards

**Comment by ad2n15** [comment]
Hi Louise,

Thank you very much for your interest,

This problem was from long time,

Now, I already implemented phesant in my research, but I am facing questions, if the implemented linear regression tool (lm) is suitable for skewed data.

As you know some UK  Biobank measures are completely skewed such as "nucleated blood cells" Data-Field 30170.

How should we deal with this problem?,

I will be in Uni of Bristol on 27th, if you would like further discuss,

Kind Regards

Ahmed Dawoud (PhD student)
Human Development and Health
University of Southampton
________________________________

**Comment by louise** [comment]
Hi Ahmed,

If you look in the PHESANT log files it should give you some info on how it dealt with each variable. PHESANT inverse rank normal transforms continuous variables to make them normal.

If a variable has >20% of the participants with the same value, PHESANT will instead convert this into an ordered categorical variable with 3 values, and tests the association with ordered logistic regression. So as an example, in my log file from my BMI MR-pheWAS it says:

30170_0|| CONTINUOUS MAIN || CONTINUOUS || >20% IN ONE CATEGORY || cat N: 321601, 1358, 1479 || CAT-ORD || order: 0|1|2 || num categories: 3 || SUCCESS results-ordered-logistic

... this says that field 30170 is a continuous field but there is >20% in one category so PHESANT converts to 3 categories with 321601, 1358 and 1479 participants in each category, and the association is then tested with ordered logistic regression.

Best wishes,

Louise

**Comment by catlisboa** [comment]
Hi! Thank you for your tool! I'm having the exact same problem, how can I solve this?
