### ISSUE TITLE
There is probably not enough contiguous virtual memory available

### ISSUE THREAD

**Issue by jiehuang001** [MRCIEU/PHESANT#12]
Dear all:

Please see the screenshot below. Can you please let me know how to resolve this memory issue?

![11](https://user-images.githubusercontent.com/26947455/72933070-fbaf0d00-3d9b-11ea-9ab0-4735facd5207.JPG)

I used the default "../variable-info/outcome-info.tsv" and "../variable-info/data-coding-ordinal-info.txt" file that comes with the download. Does these two files contain all the variables and data codings existing in the whole UKB dataset, or should I use my own version based on the data that I got from my UKB application? 

Thank you very much & best regards,
Jie

**Comment by louise** [comment]
You could try running PHESANT with a larger number of parts (e.g. 200), which should reduce the memory requirements in each part. If you are not already using HPC then that would also help.
