### ISSUE TITLE
Exclusion codes

### ISSUE THREAD

**Issue by julkunh** [MRCIEU/PHESANT#14]
Hi,

Thank you for the great tool! Would it be possible to get the meanings for some of the exclusion codes not mentioned here, e.g. "YES-POLYMORPHIC" and "YES-PROCESSING"? 

Best regards,
Heli

**Comment by louise** [comment]
Hi Heli,

Thanks for raising this. I've now added these to the description on the main page of this repository.

Best wishes,

Louise
