### ISSUE TITLE
Standard deviation change - negative values

### ISSUE THREAD

**Issue by catlisboa** [MRCIEU/PHESANT#16]
Hi! I'm facing now another issue. I'm not sure how to interpret negative values for "Standard deviation change" - I have some in the forest plots for continuous data. Could you explain me very briefly?
Sorry for this, and thank you very much!

**Comment by louise** [comment]
Continuous outcomes are inverse rank normal transformed by PHESANT. Therefore an association of e.g. -1 would mean:

Each unit increase of your exposure variable, is associated with a 1 SD lower inverse rank normal transformed outcome variable.

If you are using the standardise=TRUE PHESANT argument (which is default), then it means:
Each SD increase of your exposure variable, is associated with a 1 SD lower inverse rank normal transformed outcome variable.
