### ISSUE TITLE
I'm getting no pvals or upper and lower vals when merging - any idea why?

### ISSUE THREAD

**Issue by catlisboa** [MRCIEU/PHESANT#17]
Hi! I'm getting no pvals or upper and lower vals when merging - any ideas why?

This is the output I just got when trying to merge the results I have:
[1] "Finished flow counts"
[1] "Finished combining results"
[1] "Finished adding variable descriptions to results listing"
[1] "Number not exposure variable: 4"
[1] "Bonferroni threshold: Inf"
[1] "Number below Bonferroni threshold: 0"
Error in plot.window(...) : need finite 'xlim' values
Calls: makeQQPlot -> plot -> plot.default -> localWindow -> plot.window
In addition: Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf
3: In min(x) : no non-missing arguments to min; returning Inf
4: In max(x) : no non-missing arguments to max; returning -Inf

Results-combined file looks like this:
results-combined.txt 
```
varName	varType	n	beta	lower	upper	pvalue	resType	description	isTraitOfInterest	Cat1_ID	Cat1_Title	Cat2_ID	Cat2_Title	Cat3_ID	Cat3_Title	Category	Path
30500	CONTINUOUS	12859	2.96296172553485	NaN	NaN		LINEAR	X1		100078	Biological samples	100079	Assay results	100083	Urine assays	100083	Biological samples > Assay results > Urine assays
30510	CONTINUOUS	41336	-0.809090412411477	NaN	NaN		LINEAR	X2		100078	Biological samples	100079	Assay results	100083	Urine assays	100083	Biological samples > Assay results > Urine assays
30520	CONTINUOUS	41248	-0.599738028158548	NaN	NaN		LINEAR	X3		100078	Biological samples	100079	Assay results	100083	Urine assays	100083	Biological samples > Assay results > Urine assays
30530	CONTINUOUS	41249	-0.353154675655689	NaN	NaN		LINEAR	X4		100078	Biological samples	100079	Assay results	100083	Urine assays	100083	Biological samples > Assay results > Urine assays
```

variable-flow-counts-combined.txt looks like this:
```
name,countValue
catSin.onevalue,8
cont.main,4
excluded.catSin,3
excluded.cont,1
excluded.int,1
notinphenofile,4
start.catSin,8
start.cont,4
success.continuous,4
```

Thank you so much

**Comment by louise** [comment]
Please provide a minimal working example, i.e. results files that are input to the results processing script, that I can use to debug (preferably a small subset that still causes the issue).
