### ISSUE TITLE
Error in `$<-.data.frame`(`*tmp*`, "Cat1_Title", value = "")

### ISSUE THREAD

**Issue by catlisboa** [MRCIEU/PHESANT#18]
Hi! I had this issue before, but I'd deleted the files. Now it is happening again:

[1] "Finished flow counts"
[1] "Finished combining results"
Error in `$<-.data.frame`(`*tmp*`, "Cat1_Title", value = "") : 
  replacement has 1 row, data has 0
Calls: addVariableDescriptions -> $<- -> $<-.data.frame
Execution halted

I'm guessing because of this: (this is an excert of my results-log.txt file)
```
23038_0|| INTEGER || CONTINUOUS || >20% IN ONE CATEGORY || Bin 1: <3, bin 2: >=3AND < 25, bin 3: >=25 || cat N: 221, 266, 247 || SKIP 2 bins are too small || 
23039_0|| INTEGER || CONTINUOUS || IRNT || CONTINUOUS-SKIP-500 (371) || 
23040_0|| INTEGER || CONTINUOUS || IRNT || ERROR: 23040 Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...): 0 (non-NA) cases
```

**Comment by louise** [comment]
Please provide a minimal working example, i.e. results files that are input to the results processing script, that I can use to debug (preferably a small subset that still causes the issue).
