### ISSUE TITLE
Warning message, apparently from testCatSingle.r

### ISSUE THREAD

**Issue by AldoCP** [MRCIEU/PHESANT#2]
Hi, 

Thanks for the great work with PHESANT! Things seem to run smoothly on my end, but I get the following warning message when running "phenomeScan.r": 

> Warning messages:
> 1: In if (is.na(ordered)) { :
>   the condition has length > 1 and only the first element will be used
> 2: In if (ordered == 0) { :
>   the condition has length > 1 and only the first element will be used
> 3: In if (is.na(ordered)) { :
>   the condition has length > 1 and only the first element will be used
> 4: In if (ordered == 0) { :
>   the condition has length > 1 and only the first element will be used
> 5: In if (ordered == 1) { :
>   the condition has length > 1 and only the first element will be used
> 6: In if (is.na(ordered)) { :
>   the condition has length > 1 and only the first element will be used
> 7: In if (ordered == 0) { :
>   the condition has length > 1 and only the first element will be used
> 8: In if (ordered == 1) { :
>   the condition has length > 1 and only the first element will be used
> Warning messages:
> 1: In if (is.na(ordered)) { ... :
>   the condition has length > 1 and only the first element will be used
> 2: In if (ordered == 0) { ... :
>   the condition has length > 1 and only the first element will be used
> 3: In if (is.na(ordered)) { ... :
>   the condition has length > 1 and only the first element will be used
> 4: In if (ordered == 0) { ... :
>   the condition has length > 1 and only the first element will be used
> 5: In if (ordered == 1) { ... :
>   the condition has length > 1 and only the first element will be used
> 6: In if (is.na(ordered)) { ... :
>   the condition has length > 1 and only the first element will be used
> 7: In if (ordered == 0) { ... :
>   the condition has length > 1 and only the first element will be used
> 8: In if (ordered == 1) { ... :
>   the condition has length > 1 and only the first element will be used

The command I'm using is: 

```
Rscript phenomeScan.r \
--phenofile="${datadir}/phenofile.csv" \
--traitofinterestfile="${datadir}/exposurefile.csv" \
--variablelistfile="${phesantdir}/variable-info/outcome-info.tsv" \
--datacodingfile="${phesantdir}/variable-info/data-coding-ordinal-info.txt" \
--traitofinterest="trait1" \
--resDir="${datadir}/results/" \
--userId="subjectID" \
--save 
```

The output files (data-binary-all.txt, data-catord-all.txt, data-catunord-all.txt, data-cont-all.txt, data-log-all.txt and variable-flow-counts-all.txt) seem fine, and I think the warning message comes from "testCatSingle.r". I wonder whether it's ok to neglect it... or should I be concerned? 

Thanks! 

P.S.: On another topic: is it fine to use either continuous or binary (0/1) features as trait of interest?

**Comment by louise** [comment]
Dear AldoCP, 

Firstly, apologies for the delayed reply and thanks very much for pointing this out. This warning was because of a duplicate row in the data coding information file and would not have affected your results. I have now removed this row.

Yes it is fine to use continuous or binary as the trait of interest. If you use binary then I would advise that you use the 'standardise=FALSE' option.

Best wishes, Louise
