### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by kvedes** [MRCIEU/PHESANT#20]
Hi

I'm facing a couple of issues installing PHESANT. It doesn't seem to be available on CRAN, and I cannot install it using the devtools `install_github` command. Installing from source also doesn't work.
Is PHESANT not a library, but rather a collection of files? - Or should it be possible to install it? - If so I would much appreciate some instructions.

Br.
Kvedes

**Comment by louise** [comment]
PHESANT is software package for running phenome scans. You do not need to install it, you should download it and then call the main script phenomeScan.r, with arguments as specified on the main README of this GitHub repository [https://github.com/MRCIEU/PHESANT]. If you have difficulty please provide a minimal working example demonstrating the issues you are encountering.

We plan to make it available on CRAN or using install_github when possible.
