### ISSUE TITLE
Phecode IDs are not included by PHESANT

### ISSUE THREAD

**Issue by Shicheng-Guo** [MRCIEU/PHESANT#25]
I am wondering whether Phecode IDs are not included by PHESANT, if not, any plan to integrate to PHESANT workflow? Thanks. Shicheng

**Comment by louise** [comment]
We have no plans to use phecodes at present as PHESANT uses the 'first occurence' variables for disease outcomes (https://biobank.ctsu.ox.ac.uk/crystal/label.cgi?id=1712), which should give the most statistical power as they are manually curated variables derived from multiple sources.
