### ISSUE TITLE
Any plans to support newer versions of R?

### ISSUE THREAD

**Issue by parkcc** [MRCIEU/PHESANT#26]
For instance 4.1.1

I do realize that you may need to freeze development for such a large project.

Thanks for your help, 
Chris Park
cpark1@illlumina.com

**Comment by louise** [comment]
Hi Chris, PHESANT should run fine with later version of R. E.g. see our recent MR-pheWAS of insomnia uses R 4.0.1

https://github.com/MRCIEU/PHESANT-MR-PheWAS-Insomnia/blob/master/g_PHESANT_analysis/

I have also just tested with R 4.1.2.

Please let me know if you are encountering specific problems, and apologies for the slow response.
