### ISSUE TITLE
Removing NAs from confounder data BEFORE turning assessment center into indicator variable & merging

### ISSUE THREAD

**Issue by IttaiEres** [MRCIEU/PHESANT#27]
Hello,

Thanks for providing this very helpful package. I encountered an issue with my confounders today:

`[1] "Validating phenotype data ..."`
`[1] "Number of columns in phenotype file: 21186"`
`[1] "Phenotype file validated"`
`[1] "Validating trait of interest data ..."`
`[1] "Number of columns in trait of interest file:2"`
`[1] "Trait of interest file validated"`
`[1] "Loading phenotypes ..."`
`[1] "1 - 7062"`
`[1] "Loading trait of interest file ..."`
`[1] "Loading confounders from phenotypes file ..."`
`[1] "Adjusting for age, sex and assessment centre"`
`Error in data.frame(..., check.names = FALSE) :`
`  arguments imply differing number of rows: 502422, 502421`
`Calls: loadData -> loadConfounders -> cbind -> cbind -> data.frame`
`Execution halted`

I was able to solve this issue by simply moving up the following lines of code (97-101) in loadConfounders.r above lines 84-90 (where my assessment centers were being turned into indicator variables):

`print(paste("Number of rows in confounder data: ", nrow(confs),sep=""))`
`confsComp = complete.cases(confs)`
`print(paste("Number of INCOMPLETE rows removed from confounder data: ", length(which(confsComp==FALSE)),sep=""))`
`confs = confs[confsComp==TRUE,]`
`print(paste("Number of rows in confounder data: ", nrow(confs),sep=""))`

Again, thanks for providing this code, and hope this is a helpful small fix for when assessment center is NA for any individual in the confounder loading process.

Cheers,
Ittai

**Comment by louise** [comment]
Thanks very much Ittai, this is fixed now. I'm a bit surprised you have a NA assessment centre, so might be worth checking your data (e.g. that something hasn't gone wrong with the column separators).
