### ISSUE TITLE
Ordered Logistic Regression p-values appear to depend on scaling (standardisation) of the exposure 

### ISSUE THREAD

**Issue by pjawinski** [MRCIEU/PHESANT#28]
Hi there,

I noticed that changing the scale of the exposure variable (e.g., via standardise=TRUE or standardise=FALSE) may result in tremendous changes in p-values for ordered logistic regression results. In my specific case, standardising the exposure variable revealed p-values of 0 and VERY narrow confidence intervals that would suggest extremely large effect sizes (converted to a correlation coefficient, results would suggest effect sizes of r > 0.9). In contrast, using the unstandardised exposure variable revealed much more realistic results (associations corresponding to r < 0.1)

I googled a bit and found that someone previously mentioned that summary() of an object derived from ordered logistic regression function polr() may not show reliable t-values (https://r-help.stat.math.ethz.narkive.com/gFt6WSvk/r-bugs-and-misfeatures-in-polr-mass-fixed):

> I'm not convinced the t values reported by summary() are
reliable. I've noticed that a one dimensional linear transformation
the independent variables can cause the reported t values to change by
a factor of more than 100, which doesn't seem right.

I tried around with the polr() function myself and observed exactly the same phenomenon.

Importantly, I've seen the same issue of p-values-depend-on-exposure-scaling for the multinomial logistic results, but only for particular categories (as listed in results-multinomial-logistic-all.txt) and NOT for the overall association tests (which are passed to results-combined.txt). Interestingly, for the multinomial overall association test, you compare the full model (variable of interest + confounders) against the base model (confounders only) using a likelihood ratio test. I thought this may also be a sensible solution for the ordered logistic regression and thus, I slightly changed the code of PHESANT/WAS/testCategoricalOrdered.r as follows starting at line 77:

```
fit <- polr(phenoFactor ~ geno + ., data=confounders, Hess=TRUE) 

## added by PJ: baseline model with only confounders, to which we compare the model above
fitB <- polr(phenoFactor ~ ., data=confounders, Hess=TRUE)

## added by PJ: compare model to baseline model
lres = anova(fit, fitB)
modelP = pchisq(lres[2,"LR stat."], df=lres[2,"   Df"], lower.tail=FALSE) 

ctable <- coef(summary(fit))
sink()
sink(resLogFile, append=TRUE)

ct = coeftest(fit)
pvalue = modelP ## line modified by PJ, original line: pvalue = ct["geno","Pr(>|t|)"]
beta = ctable["geno", "Value"];
```

By comparing the full and base model via the likelihood ratio test of function anova(), p-values of the ordered logistic regression do not appear to depend on the exposure variable-scaling anymore, so standardised=TRUE and standardised=FALSE reveal virtually identical p-values. I used function anova() instead of lrtest(), because in very rare cases (1-3 out of several thousands of Biobank variables), there was still some degree of descrepancy between the standardised vs. unstandardised analysis when using lrtest(). So anova() might be somewhat more reliable. It should also be noted that I re-calculated the p-value of the anova() likelihood ratio test (see `pchisq` above), because the build-in anova p-value appeared to have limited precision (p-values < 1E-10 were set to 0).

By the way, I ran the analyses using different R and R package versions first, because I expected this issue to be solved when using up2date package versions or the exact same package versions specified under Requirements at the main PHESANT GitHub page. However, that did not solve the issues.

I just wanted to share my experiences with you and hope it might be helpful. Maybe someone else runs into the same issue. Might be worth looking into! If you have a plausible explanation or other solutions, I would be very much interested to here them. I attached my conda-environment for reasons of reproducibility (uploaded as .txt, otherwise not accepted): [phesant.yml.txt](https://github.com/MRCIEU/PHESANT/files/7736991/phesant.yml.txt)

Best wishes,
Philippe

**Comment by louise** [comment]
Thanks very much Philippe for this detailed comment. The ordered regression p value now uses a likelihood ratio test.
