### ISSUE TITLE
Guidance on how to analyze a large UKB dataset

### ISSUE THREAD

**Issue by vforget** [MRCIEU/PHESANT#29]
Hi,

PHEASANT is a wonderful tool. I can't image how we would run UKB pheWAS without it!

I want to use PHEASANT to run a pheWAS using a PRS as input. If I understand correctly I add the PRS as a column to the `phenofile` and define this variable as a trait of interest. However, my UKB `phenofile` is quite large, with thousands of variables and I would like to avoid building a new `phenofile` every time I obtain a new variable (such as a new PRS).

So, did I understand how PHEASANT works, and if so, any guidance on how to address my concern?

Thanks!

**Comment by louise** [comment]
Hi Vince,

Thanks for your query. Your PRS should be supplied in a separate file. This will be your trait of interest file, that you can specify using the traitofinterestfile argument (see here https://github.com/MRCIEU/PHESANT/). You could have several PRS (or other 'traits of interest') in that file, then you can use the traitofinterest argument to specify which you want to use for each phenome scan.

Hope that's clear, and good luck with your project.

Louise
