### ISSUE TITLE
Test File for Genetic Data to be given as input file

### ISSUE THREAD

**Issue by sawantaniket461** [MRCIEU/PHESANT#31]
Dear Authors,

Could you please provide the format which is acceptable by PHESANT as input for genetic data?

Also,
Is there any possibility to get all the p-values of all the tests performed? I tried finding these in the results file before executing the "Post phenome scan results processing step" and also after it, but the output contains only those results which are significant. I would like to know a possible way to modify this so as to understand the association parameters of all the phenotypes.

Regards,
Aniket

**Comment by louise** [comment]
Please see information here https://github.com/MRCIEU/PHESANT/, and example data here https://github.com/MRCIEU/PHESANT/

PHESANT outputs all results from the scan, not just those that are 'significant'.
