### ISSUE TITLE
Failed to export recoded phenofiles without any analysis

### ISSUE THREAD

**Issue by huangyuanf** [MRCIEU/PHESANT#33]
Hi,

I use the argument save to export recoded phenofiles without any analysis as such ,but failed ,how can I realize this

cd WAS/
Rscript phenomeScan.r \
--phenofile="${testDir}data/phenotypes.csv"  \
--traitofinterestfile=--traitofinterestfile="${testDir}data/exposure.csv" \
--variablelistfile="../variable-info/outcome-info.tsv" \
--datacodingfile="../variable-info/data-coding-ordinal-info.csv" \
--resDir=--resDir="${testDir}results/" \
--userId="userId"\
--save=TRUE\

erro:
Error in getopt(spec = spec, opt = args) :
  long flag "save" accepts no arguments
Calls: parse_args -> getopt
Execution halted

**Comment by louise** [comment]
Bits of that command don't look right e.g. 
--traitofinterestfile=--traitofinterestfile=
same for the resDir line. 
The trait of interest arg isn't required if you are saving the data (no trait of interest needed).
you should just use --save not --save=TRUE
Here is an example: https://github.com/MRCIEU/PHESANT-MR-pheWAS-smoking/blob/master/2-PHESANT/sample-all-save/j1.sh
