### ISSUE TITLE
Error: computing correlation between genotype and other phenotypes from UKB

### ISSUE THREAD

**Issue by zqsha** [MRCIEU/PHESANT#35]
Hi expert,
Recently, I wanted to compute the correlation between genotype (i.e. 0/1/2 corresponding to AA/AB/BB) and other clinical phenotypes from UKB. I used the following command line to run this analysis
Rscript phenomeScan.r \
--phenofile=test.csv \
--traitofinterestfile=pheno_input.csv \
--confounderfile=covariate_input.csv \
--variablelistfile=/PHESANT/variable-info/outcome-info.tsv \
--datacodingfile=/PHESANT/variable-info/data-coding-ordinal-info.txt \
--traitofinterest=genotype \
--resDir=/results/ \
--userId=SID

But, it reported the following error,
19_0|| CAT-SINGLE || Inc(>=10): 1(17018) || Inc(>=10): 2(3304) || Inc(>=10): 3(137) || CAT-SINGLE-UNORDERED || reference: 1=17018 || ERROR: 19 Error in multinom(phenoFactor ~ geno + ., data = confounders, maxit = 1000): need two or more classes to fit a multinom model
21_0|| CAT-SINGLE || Inc(>=10): 1(30657) || Inc(>=10): 3(341) || Inc(>=10): 4(17) || CAT-SINGLE-UNORDERED || reference: 1=30657 || ERROR: 21 Error in multinom(phenoFactor ~ geno + ., data = confounders, maxit = 1000): need two or more classes to fit a multinom model
31_0|| Excluded cat-single: YES-SEX || 
34_0|| Excluded integer: YES-AGE || 
36_0 || Variable could not be found in pheno info file. 
37_0 || Variable could not be found in pheno info file. 
38_0 || Variable could not be found in pheno info file. 
39_0 || Variable could not be found in pheno info file. 
40_0 || Variable could not be found in pheno info file. 
41_0 || Variable could not be found in pheno info file. 
42_0 || Variable could not be found in pheno info file. 
43_0 || Variable could not be found in pheno info file. 
44_0 || Variable could not be found in pheno info file. 
45_0 || Variable could not be found in pheno info file. 
46_0|| INTEGER || CONTINUOUS || IRNT || ERROR: 46 Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...): 0 (non-NA) cases
47_0|| INTEGER || CONTINUOUS || IRNT || ERROR: 47 Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...): 0 (non-NA) cases
48_0|| CONTINUOUS MAIN || CONTINUOUS || IRNT || ERROR: 48 Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...): 0 (non-NA) cases
49_0|| CONTINUOUS MAIN || CONTINUOUS || IRNT || ERROR: 49 Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...): 0 (non-NA) cases
50_0|| CONTINUOUS MAIN || CONTINUOUS || IRNT || ERROR: 50 Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...): 0 (non-NA) cases
51_0|| CONTINUOUS MAIN || CONTINUOUS || IRNT || ERROR: 51 Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...): 0 (non-NA) cases
52_0|| Excluded cat-single: YES-AGE || 
54_0|| Excluded cat-single: YES-ASSESSMENT-CENTRE || 
55_0|| CAT-SINGLE || Inc(>=10): 6(3533) || Inc(>=10): 12(1698) || Inc(>=10): 4(2420) || Inc(>=10): 9(2450) || Inc(>=10): 5(3091) || Inc(>=10): 3(3155) || Inc(>=10): 2(2691) || Inc(>=10): 8(2497) || Inc(>=10): 7(2891) || Inc(>=10): 11(2365) || Inc(>=10): 10(2253) || Inc(>=10): 1(1982) || CAT-SINGLE-UNORDERED || reference: 6=3533 || ERROR: 55 Error in multinom(phenoFactor ~ geno + ., data = confounders, maxit = 1000): need two or more classes to fit a multinom model
77_0|| CONTINUOUS MAIN || CONTINUOUS || IRNT || ERROR: 77 Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...): 0 (non-NA) cases
78_0|| CONTINUOUS MAIN || CONTINUOUS || IRNT || ERROR: 78 Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...): 0 (non-NA) cases
84_0|| INTEGER || reassignments: -3=NA|-1=NA || CONTINUOUS || IRNT || ERROR: 84 Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...): 0 (non-NA) cases
87_0|| Excluded integer: YES-POLYMORPHIC || 
93_0|| INTEGER || CONTINUOUS || IRNT || ERROR: 93 Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...): 0 (non-NA) cases
94_0|| INTEGER || CONTINUOUS || IRNT || ERROR: 94 Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...): 0 (non-NA) cases
95_0|| INTEGER || CONTINUOUS || IRNT || ERROR: 95 Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...): 0 (non-NA) cases
96_0|| INTEGER || CONTINUOUS || IRNT || ERROR: 96 Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...): 0 (non-NA) cases
102_0|| INTEGER || CONTINUOUS || IRNT || ERROR: 102 Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...): 0 (non-NA) cases
120_0|| CAT-SINGLE || Inc(>=10): 1(18710) || Inc(>=10): 9(12130) || Inc(>=10): 2(186) || CAT-SINGLE-UNORDERED || reference: 1=18710 || ERROR: 120 Error in multinom(phenoFactor ~ geno + ., data = confounders, maxit = 1000): need two or more classes to fit a multinom model
129_0|| INTEGER || CONTINUOUS || IRNT || ERROR: 129 Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...): 0 (non-NA) cases
130_0|| INTEGER || CONTINUOUS || IRNT || ERROR: 130 Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...): 0 (non-NA) cases
134_0|| INTEGER || Inc(>=10): 0(29116) || Inc(>=10): 1(1825) || Inc(>=10): 2(80) || Removed 3: 5<10 examples || 3-20 values || CAT-ORD || order: 0|1|2 || num categories: 3 || ERROR: 134 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
135_0 || Variable could not be found in pheno info file. 
137_0|| INTEGER || CONTINUOUS || >20% IN ONE CATEGORY || Bin 1: ==0, bin 2: > 0 AND <2bin 3: >=2 || cat N: 10628, 6456, 13942 || CAT-ORD || order: 0|1|2 || num categories: 3 || ERROR: 137 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
189_0|| CONTINUOUS MAIN || CONTINUOUS || IRNT || ERROR: 189 Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...): 0 (non-NA) cases
396_0|| INTEGER || Inc(>=10): 3.5(30900) || SKIP (number of levels: 1)
397_0|| INTEGER || Inc(>=10): 2.5(30900) || SKIP (number of levels: 1)
398_0|| INTEGER || Inc(>=10): 4.5(30584) || Inc(>=10): 0(108) || Inc(>=10): 2.5(19) || Inc(>=10): 2(43) || Inc(>=10): 3(53) || Inc(>=10): 1.5(62) || Inc(>=10): 0.5(11) || Inc(>=10): 3.5(12) || Removed 1: 7<10 examples || Removed 4: 1<10 examples || 3-20 values || CAT-ORD || order: 0|0.5|1.5|2|2.5|3|3.5|4.5 || num categories: 8 || ERROR: 398 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
399_0|| INTEGER || CONTINUOUS || IRNT || ERROR: 399 Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...): 0 (non-NA) cases
400_0|| INTEGER || reassignments: 0=NA || CONTINUOUS || IRNT || ERROR: 400 Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...): 0 (non-NA) cases
401_0|| Excluded cat-single: YES-CAT-SIN-MUL-VAL || 
402_0|| Excluded cat-single: YES-CAT-SIN-MUL-VAL || 
403_0|| INTEGER || CONTINUOUS || >20% IN ONE CATEGORY || Bin 1: <0.5, bin 2: ==0.5, bin 3: >0.5 || cat N: 263, 27682, 2935 || CAT-ORD || order: 0|1|2 || num categories: 3 || ERROR: 403 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
404_0|| INTEGER || CONTINUOUS || IRNT || ERROR: 404 Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...): 0 (non-NA) cases
670_0|| CAT-SINGLE || Inc(>=10): 1(29106) || Inc(>=10): 2(1853) || Inc(>=10): 3(18) || Inc(>=10): 4(13) || CAT-SINGLE-UNORDERED || reference: 1=29106 || ERROR: 670 Error in multinom(phenoFactor ~ geno + ., data = confounders, maxit = 1000): need two or more classes to fit a multinom model
680_0|| CAT-SINGLE || Inc(>=10): 2(13262) || Inc(>=10): 1(16239) || Inc(>=10): 4(556) || Inc(>=10): 3(510) || Inc(>=10): 6(178) || Inc(>=10): 5(52) || CAT-SINGLE-UNORDERED || reference: 1=16239 || ERROR: 680 Error in multinom(phenoFactor ~ geno + ., data = confounders, maxit = 1000): need two or more classes to fit a multinom model
699_0|| INTEGER || reassignments: -1=NA|-3=NA|-10=NA || CONTINUOUS || IRNT || ERROR: 699 Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...): 0 (non-NA) cases
709_0 || Variable could not be found in pheno info file. 
728_0|| CAT-SINGLE || Inc(>=10): 2(11323) || Inc(>=10): 3(14243) || Inc(>=10): 1(1103) || Inc(>=10): 4(3279) || Inc(>=10): 5(978) || ordered || CAT-ORD || order: 1|2|3|4|5 || num categories: 5 || ERROR: 728 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
738_0|| CAT-SINGLE || Inc(>=10): 3(8599) || Inc(>=10): 2(6193) || Inc(>=10): 1(3222) || Inc(>=10): 5(2165) || Inc(>=10): 4(8160) || ordered || CAT-ORD || order: 1|2|3|4|5 || num categories: 5 || ERROR: 738 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
757_0|| INTEGER || reassignments: -1=NA|-3=NA|-10=NA || CONTINUOUS || IRNT || ERROR: 757 Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...): 0 (non-NA) cases
767_0|| INTEGER || reassignments: -1=NA|-3=NA || CONTINUOUS || IRNT || ERROR: 767 Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...): 0 (non-NA) cases
777_0|| INTEGER || CONTINUOUS || >20% IN ONE CATEGORY || Bin 1: <4, bin 2: >=4AND < 5, bin 3: >=5 || cat N: 5707, 2646, 13068 || CAT-ORD || order: 0|1|2 || num categories: 3 || ERROR: 777 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
796_0|| INTEGER || reassignments: -1=NA|-3=NA|-10=NA || CONTINUOUS || IRNT || ERROR: 796 Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...): 0 (non-NA) cases
806_0|| CAT-SINGLE || Inc(>=10): 1(8923) || Inc(>=10): 3(2871) || Inc(>=10): 2(6902) || Inc(>=10): 4(2804) || ordered || CAT-ORD || order: 1|2|3|4 || num categories: 4 || ERROR: 806 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
816_0|| CAT-SINGLE || Inc(>=10): 1(15842) || Inc(>=10): 3(1007) || Inc(>=10): 2(3900) || Inc(>=10): 4(759) || ordered || CAT-ORD || order: 1|2|3|4 || num categories: 4 || ERROR: 816 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
826_0|| CAT-SINGLE || Inc(>=10): 1(18539) || Inc(>=10): 4(1315) || Inc(>=10): 2(1310) || Inc(>=10): 3(324) || ordered || CAT-ORD || order: 1|2|3|4 || num categories: 4 || ERROR: 826 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
845_0|| INTEGER || reassignments: -1=NA|-2=NA|-3=NA || CONTINUOUS || >20% IN ONE CATEGORY || Bin 1: <16, bin 2: >=16AND < 17, bin 3: >=17 || cat N: 3213, 5677, 7654 || CAT-ORD || order: 0|1|2 || num categories: 3 || ERROR: 845 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
864_0|| INTEGER || reassignments: -1=NA|-2=NA|-3=NA || Inc(>=10): 6(3074) || Inc(>=10): 5(4947) || Inc(>=10): 3(2718) || Inc(>=10): 7(13400) || Inc(>=10): 0(615) || Inc(>=10): 2(2191) || Inc(>=10): 4(2799) || Inc(>=10): 1(1103) || 3-20 values || CAT-ORD || order: 0|1|2|3|4|5|6|7 || num categories: 8 || ERROR: 864 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
874_0|| INTEGER || reassignments: -1=NA|-3=NA || CONTINUOUS || IRNT || ERROR: 874 Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...): 0 (non-NA) cases
884_0|| INTEGER || reassignments: -1=NA|-3=NA || Inc(>=10): 6(1524) || Inc(>=10): 7(4929) || Inc(>=10): 5(4174) || Inc(>=10): 2(4955) || Inc(>=10): 1(2968) || Inc(>=10): 3(5000) || Inc(>=10): 4(3148) || Inc(>=10): 0(3615) || 3-20 values || CAT-ORD || order: 0|1|2|3|4|5|6|7 || num categories: 8 || ERROR: 884 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
894_0|| INTEGER || reassignments: -1=NA|-3=NA || CONTINUOUS || >20% IN ONE CATEGORY || Bin 1: <30, bin 2: >=30AND < 60, bin 3: >=60 || cat N: 7789, 7165, 9612 || CAT-ORD || order: 0|1|2 || num categories: 3 || ERROR: 894 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
904_0|| INTEGER || reassignments: -1=NA|-3=NA || Inc(>=10): 3(4726) || Inc(>=10): 2(5393) || Inc(>=10): 4(2184) || Inc(>=10): 0(9996) || Inc(>=10): 1(5006) || Inc(>=10): 5(1895) || Inc(>=10): 6(555) || Inc(>=10): 7(773) || 3-20 values || CAT-ORD || order: 0|1|2|3|4|5|6|7 || num categories: 8 || ERROR: 904 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
914_0|| INTEGER || reassignments: -1=NA|-3=NA || CONTINUOUS || IRNT || ERROR: 914 Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...): 0 (non-NA) cases
924_0|| CAT-SINGLE || Inc(>=10): 2(14418) || Inc(>=10): 3(15717) || Inc(>=10): 1(846) || ordered || CAT-ORD || order: 1|2|3 || num categories: 3 || ERROR: 924 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
943_0|| CAT-SINGLE || Inc(>=10): 4(2970) || Inc(>=10): 2(11878) || Inc(>=10): 3(6407) || Inc(>=10): 1(5294) || Inc(>=10): 5(2169) || Inc(>=10): 0(2105) || ordered || CAT-ORD || order: 0|1|2|3|4|5 || num categories: 6 || ERROR: 943 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
971_0|| CAT-SINGLE || Inc(>=10): 5(2253) || Inc(>=10): 2(7600) || Inc(>=10): 4(5143) || Inc(>=10): 1(2179) || Inc(>=10): 6(2223) || Inc(>=10): 3(4465) || ordered || CAT-ORD || order: 1|2|3|4|5|6 || num categories: 6 || ERROR: 971 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
981_0|| CAT-SINGLE || Inc(>=10): 3(8306) || Inc(>=10): 4(4319) || Inc(>=10): 7(2392) || Inc(>=10): 6(1988) || Inc(>=10): 5(2282) || Inc(>=10): 2(4288) || Inc(>=10): 1(257) || ordered || CAT-ORD || order: 1|2|3|4|5|6|7 || num categories: 7 || ERROR: 981 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
991_0|| CAT-SINGLE || Inc(>=10): 4(1822) || Inc(>=10): 3(1109) || Inc(>=10): 2(683) || Inc(>=10): 5(632) || Inc(>=10): 1(252) || Inc(>=10): 6(66) || ordered || CAT-ORD || order: 1|2|3|4|5|6 || num categories: 6 || ERROR: 991 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
1001_0|| CAT-SINGLE || Inc(>=10): 3(1949) || Inc(>=10): 4(1367) || Inc(>=10): 7(174) || Inc(>=10): 5(513) || Inc(>=10): 2(302) || Inc(>=10): 6(221) || Inc(>=10): 1(42) || ordered || CAT-ORD || order: 1|2|3|4|5|6|7 || num categories: 7 || ERROR: 1001 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
1011_0|| CAT-SINGLE || Inc(>=10): 1(1433) || Inc(>=10): 2(5041) || Inc(>=10): 3(3983) || Inc(>=10): 6(874) || Inc(>=10): 5(1488) || Inc(>=10): 4(4562) || ordered || CAT-ORD || order: 1|2|3|4|5|6 || num categories: 6 || ERROR: 1011 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
1021_0|| CAT-SINGLE || Inc(>=10): 7(841) || Inc(>=10): 3(5578) || Inc(>=10): 2(3962) || Inc(>=10): 5(1827) || Inc(>=10): 4(3013) || Inc(>=10): 6(1242) || Inc(>=10): 1(824) || ordered || CAT-ORD || order: 1|2|3|4|5|6|7 || num categories: 7 || ERROR: 1021 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
1031_0|| CAT-SINGLE || reassignments: 7=6 || Inc(>=10): 4(4672) || Inc(>=10): 3(11676) || Inc(>=10): 6(301) || Inc(>=10): 1(2966) || Inc(>=10): 5(1991) || Inc(>=10): 2(9224) || ordered || CAT-ORD || order: 1|2|3|4|5|6 || num categories: 6 || ERROR: 1031 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
1050_0|| INTEGER || reassignments: -1=NA|-3=NA|-10=NA || CONTINUOUS || >20% IN ONE CATEGORY || Bin 1: <2, bin 2: >=2AND < 4, bin 3: >=4 || cat N: 3810, 13084, 11481 || CAT-ORD || order: 0|1|2 || num categories: 3 || ERROR: 1050 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
1060_0|| INTEGER || reassignments: -1=NA|-3=NA|-10=NA || Inc(>=10): 4(1308) || Inc(>=10): 1(11020) || Inc(>=10): 3(2184) || Inc(>=10): 2(6768) || Inc(>=10): 5(551) || Inc(>=10): 12(14) || Inc(>=10): 6(363) || Inc(>=10): 0(973) || Inc(>=10): 8(245) || Inc(>=10): 9(42) || Inc(>=10): 7(110) || Inc(>=10): 10(79) || Removed 20: 3<10 examples || Removed 15: 2<10 examples || Removed 24: 1<10 examples || Removed 14: 1<10 examples || Removed 11: 2<10 examples || Removed 22: 1<10 examples || 3-20 values || CAT-ORD || order: 0|1|2|3|4|5|6|7|8|9|10|12 || num categories: 12 || ERROR: 1060 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
1070_0|| INTEGER || reassignments: -1=NA|-3=NA|-10=NA || Inc(>=10): 3(6922) || Inc(>=10): 5(1525) || Inc(>=10): 0(1179) || Inc(>=10): 1(5020) || Inc(>=10): 2(9521) || Inc(>=10): 4(3915) || Inc(>=10): 10(11) || Inc(>=10): 9(10) || Inc(>=10): 6(505) || Inc(>=10): 7(87) || Inc(>=10): 8(91) || Removed 12: 5<10 examples || Removed 18: 2<10 examples || Removed 21: 2<10 examples || 3-20 values || CAT-ORD || order: 0|1|2|3|4|5|6|7|8|9|10 || num categories: 11 || ERROR: 1070 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
1080_0|| INTEGER || reassignments: -1=NA|-3=NA|-10=NA || Inc(>=10): 1(10573) || Inc(>=10): 0(4497) || Inc(>=10): 2(4492) || Inc(>=10): 3(1386) || Inc(>=10): 4(674) || Inc(>=10): 6(353) || Inc(>=10): 8(126) || Inc(>=10): 7(108) || Inc(>=10): 5(470) || Inc(>=10): 9(37) || Inc(>=10): 10(34) || Removed 12: 8<10 examples || Removed 11: 2<10 examples || Removed 15: 2<10 examples || Removed 20: 1<10 examples || 3-20 values || CAT-ORD || order: 0|1|2|3|4|5|6|7|8|9|10 || num categories: 11 || ERROR: 1080 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
1090_0|| INTEGER || reassignments: -1=NA|-3=NA|-10=NA || Inc(>=10): 1(9652) || Inc(>=10): 2(4261) || Inc(>=10): 0(3922) || Inc(>=10): 3(897) || Inc(>=10): 8(65) || Inc(>=10): 4(394) || Inc(>=10): 6(122) || Inc(>=10): 5(146) || Inc(>=10): 10(24) || Inc(>=10): 9(30) || Removed 12: 7<10 examples || Inc(>=10): 7(37) || Removed 24: 1<10 examples || Removed 11: 6<10 examples || 3-20 values || CAT-ORD || order: 0|1|2|3|4|5|6|7|8|9|10 || num categories: 11 || ERROR: 1090 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
1100_0|| CAT-SINGLE || reassignments: 5=-4 || Inc(>=10): 2(12947) || Inc(>=10): 3(4062) || Inc(>=10): 1(10586) || Inc(>=10): 4(1840) || ordered || CAT-ORD || order: 1|2|3|4 || num categories: 4 || ERROR: 1100 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
1110_0|| CAT-SINGLE || Inc(>=10): 2(4818) || Inc(>=10): 0(4023) || Inc(>=10): 4(11616) || Inc(>=10): 3(9846) || Inc(>=10): 1(572) || ordered || CAT-ORD || order: 0|1|2|3|4 || num categories: 5 || ERROR: 1110 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
1120_0|| CAT-SINGLE || Inc(>=10): 1(10575) || Inc(>=10): 0(5504) || Inc(>=10): 3(3822) || Inc(>=10): 2(4663) || Inc(>=10): 5(1076) || Inc(>=10): 4(1108) || ordered || CAT-ORD || order: 0|1|2|3|4|5 || num categories: 6 || ERROR: 1120 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
1130_0|| CAT-SINGLE || Inc(>=10): 0(21336) || Inc(>=10): 3(616) || Inc(>=10): 2(1176) || Inc(>=10): 1(3038) || Inc(>=10): 4(667) || ordered || CAT-ORD || order: 0|1|2|3|4 || num categories: 5 || ERROR: 1130 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
1140_0|| CAT-SINGLE || reorder 1|0|2 || Inc(>=10): 3(9551) || Inc(>=10): 2(13581) || Inc(>=10): 1(3398) || ordered || CAT-ORD || order: 1|0|2 || num categories: 3 || ERROR: 1140 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
1150_0|| CAT-SINGLE || Inc(>=10): 2(15467) || Inc(>=10): 3(1854) || Inc(>=10): 1(9416) || CAT-SINGLE-UNORDERED || reference: 2=15467 || ERROR: 1150 Error in multinom(phenoFactor ~ geno + ., data = confounders, maxit = 1000): need two or more classes to fit a multinom model
1160_0|| INTEGER || reassignments: -1=NA|-3=NA || Inc(>=10): 7(13582) || Inc(>=10): 8(8979) || Inc(>=10): 6(5483) || Inc(>=10): 9(1603) || Inc(>=10): 10(248) || Inc(>=10): 5(893) || Removed 14: 1<10 examples || Inc(>=10): 4(125) || Inc(>=10): 3(16) || Inc(>=10): 12(14) || Inc(>=10): 11(17) || Removed 13: 7<10 examples || Removed 2: 2<10 examples || Removed 16: 1<10 examples || 3-20 values || CAT-ORD || order: 3|4|5|6|7|8|9|10|11|12 || num categories: 10 || ERROR: 1160 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
1170_0|| CAT-SINGLE || Inc(>=10): 3(16055) || Inc(>=10): 2(4360) || Inc(>=10): 4(9427) || Inc(>=10): 1(1039) || ordered || CAT-ORD || order: 1|2|3|4 || num categories: 4 || ERROR: 1170 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
1180_0|| CAT-SINGLE || Inc(>=10): 3(8062) || Inc(>=10): 2(10247) || Inc(>=10): 1(6770) || Inc(>=10): 4(2587) || ordered || CAT-ORD || order: 1|2|3|4 || num categories: 4 || ERROR: 1180 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
1190_0|| CAT-SINGLE || Inc(>=10): 1(19381) || Inc(>=10): 2(10483) || Inc(>=10): 3(1157) || ordered || CAT-ORD || order: 1|2|3 || num categories: 3 || ERROR: 1190 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
1200_0|| CAT-SINGLE || Inc(>=10): 2(14757) || Inc(>=10): 1(8503) || Inc(>=10): 3(7751) || ordered || CAT-ORD || order: 1|2|3 || num categories: 3 || ERROR: 1200 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
1210_0|| CAT-SINGLE || Inc(>=10): 2(18742) || Inc(>=10): 1(10584) || CAT-SINGLE-BINARY || sample 10584/18742(29326) || ERROR: 1210 Error in model.matrix.default(mt, mf, contrasts): variable 1 has no levels
1220_0|| CAT-SINGLE || Inc(>=10): 0(24846) || Inc(>=10): 1(5524) || Inc(>=10): 2(619) || Removed 3: 1<10 examples || ordered || CAT-ORD || order: 0|1|2 || num categories: 3 || ERROR: 1220 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
1239_0|| CAT-SINGLE || reorder 0|2|1 || Inc(>=10): 1(29144) || Inc(>=10): 3(1200) || Inc(>=10): 2(676) || ordered || CAT-ORD || order: 0|2|1 || num categories: 3 || ERROR: 1239 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
1249_0|| CAT-SINGLE || Inc(>=10): 1(6946) || Inc(>=10): 3(5603) || Inc(>=10): 4(13279) || Inc(>=10): 2(3943) || ordered || CAT-ORD || order: 1|2|3|4 || num categories: 4 || ERROR: 1249 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
1259_0|| CAT-SINGLE || Inc(>=10): 1(2197) || Inc(>=10): 0(27211) || Inc(>=10): 2(277) || ordered || CAT-ORD || order: 0|1|2 || num categories: 3 || ERROR: 1259 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
1269_0|| INTEGER || reassignments: -1=NA|-3=NA || CONTINUOUS || >20% IN ONE CATEGORY || Bin 1: ==0, bin 2: > 0 AND <2bin 3: >=2 || cat N: 28460, 441, 629 || CAT-ORD || order: 0|1|2 || num categories: 3 || ERROR: 1269 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
1279_0|| INTEGER || reassignments: -1=NA|-3=NA || CONTINUOUS || >20% IN ONE CATEGORY || Bin 1: ==0, bin 2: ==1bin 3: >1 || cat N: 23597, 3393, 1301 || CAT-ORD || order: 0|1|2 || num categories: 3 || ERROR: 1279 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector
1289_0|| INTEGER || reassignments: -1=NA|-3=NA|-10=NA || CONTINUOUS || >20% IN ONE CATEGORY || Bin 1: <2, bin 2: >=2AND < 3, bin 3: >=3 || cat N: 5091, 10992, 14260 || CAT-ORD || order: 0|1|2 || num categories: 3 || ERROR: 1289 Error in family$linkfun(mustart): Argument mu must be a nonempty numeric vector

I guess it might be related to the coding of the genotypes. In the trait of interest file, AA/AB/BB was encoded by 0/1/2, respectively. I am not sure whether it is correct. Alternatively, do you have any thoughts about where the issue of my input file is ? Thank you so much in advance.

Best,
Cain

**Comment by louise** [comment]
Issue resolved by email – confounder file set up incorrectly (no participant ID column)
