### ISSUE TITLE
File content and structure for main analysis

### ISSUE THREAD

**Issue by FleetingA** [MRCIEU/PHESANT#36]
Hi, 

Not an issue really but a few questions regarding the content and structure of the required files to run PheWAS.

1. First, a question regarding what the file containing phenotypes should look like (I will be using my own subset of UKB data). The instructions for the **phenofile** state that this should be a 'comma separated file containing phenotypes. Each row is a participant, the first column contains the participant id and the remaining columns are phenotypes.'

I've noticed that in some of the examples, though, **user_id** tends to be included as a variable that simply orders the dataset from n1 onwards (like an index var), as opposed to being the 'eid' UKB variable containing each individual patient identifier (as derived from UKB). My question is, should the phenotype file contain the 'eid' identifier as a first column, or an indexing variable ordering the entire dataset from n(1) to n(x)? Apologies if my understanding is incorrect.

2. If users only want to use a very small subset of phenotypes to test for associations, would it be sufficient to set EXCLUDED to YES for all the variables that they are planning _not_ to use in the **outcome-info.tsv** file?

3. For users who have just recently pulled out data from UKB, would you be able to indicate which part of the script updates the **data-coding-ordinal-info.txt** file? Apologies if this is a basic question, my background is not in computing, so I'm still trying to understand the repo.

4. How should the confounder file be arranged? Does it need to match the phenofile but just contain the covariates? Does the first variable/column need to be 'userId' as well?

Many thanks in advance for your time and understanding.

**Comment by louise** [comment]
1. The userId column is the participant ID, so it is the data in the eid UK Biobank column. See https://github.com/MRCIEU/PHESANT/tree/master/testWAS for an example

3. You should include the phenotypes you want to include in the phenofile, see here – https://github.com/MRCIEU/PHESANT/tree/master

5. The data codes are updated with code in this directory – https://github.com/MRCIEU/PHESANT/tree/master/ukb_data_codes
However, you should not need to do this unless there is are a number of new variables added to UKB. If there are particular variables. If there are particular variables missing from PHESANT then you can let me know and I will look to update it.

6. See (1) above.
