### ISSUE TITLE
Error "ERROR 1990 CAT-SIN 100349" and Error in polr(phenoFactor ~ ., data = confounders, Hess = TRUE): attempt to find suitable starting values failed

### ISSUE THREAD

**Issue by FleetingA** [MRCIEU/PHESANT#38]
After running the script and inspecting the results, I notice that a very large proportion of my tested phenotypes produce the below error:

1940_2|| CAT-SINGLE || Inc(>=10): No(30795) || Inc(>=10): Yes(10353) || Inc(>=10): Do not know(1850) || Inc(>=10): Prefer not to answer(68) || [1] "ERROR 1940 CAT-SIN 100349"

1950_2|| CAT-SINGLE || Inc(>=10): No(22647) || Inc(>=10): Yes(19027) || Inc(>=10): Do not know(1346) || Inc(>=10): Prefer not to answer(46) || [1] "ERROR 1950 CAT-SIN 100349"

1990_2|| CAT-SINGLE || Inc(>=10): No(37008) || Inc(>=10): Yes(5022) || Inc(>=10): Do not know(1000) || Inc(>=10): Prefer not to answer(36) || [1] "ERROR 1990 CAT-SIN 100349"

2020_2|| CAT-SINGLE || Inc(>=10): No(36757) || Inc(>=10): Yes(5694) || Inc(>=10): Do not know(533) || Inc(>=10): Prefer not to answer(82) || [1] "ERROR 2020 CAT-SIN 100349"

or 

ERROR: 2050 Error in polr(phenoFactor ~ ., data = confounders, Hess = TRUE): attempt to find suitable starting values failed

Has anyone figured out what might be causing said errors?

Thanks in advance for any advice!

**Comment by louise** [comment]
please supply a minimal reproducible example (with test data not real data) and I can take a look.
