### ISSUE TITLE
Can the data type of the trait be specified somehow?

### ISSUE THREAD

**Issue by franrodalg** [MRCIEU/PHESANT#39]
Hi everyone!

First of all, thanks so much for your work. It is helping immensely :)

I might have missed it, but I see no way of specifying the data type of the trait of interest in the same way that the phenotypes are coded. For instance, I have a trait of interest that is essentially a probability. I assume that will be interpreted as a standard continuous variable, and I'm not sure if that assumption would affect the power to detect associations. If so, can the type be specified somehow explicitly to perhaps change the underlying behaviour?

Cheers!

**Comment by FleetingA** [comment]
Hi Fran, 

Not sure if still useful, but if I were you, I'd change the data type of the trait of interest in the outcome-info file. 

I am also working on a project where my trait of interest is a continuous variable (the original one). I made it categorical and simply changed to 'categorical single' in the outcome-info file before I reran the whole phenome scan.

Hope that helps a bit!
