### ISSUE TITLE
phenofile preparation

### ISSUE THREAD

**Issue by Conxz** [MRCIEU/PHESANT#4]
Is there any trick/quick way for preparing the phenofile from the UKB data file? I think some edits should be done before input the ukbiobank .tab file to phenomeScan.r. 
Renameing variable name into the format 'x[varid]_[instance]_[array]' is the only edit?
Thanks.

**Comment by Conxz** [comment]
to answer my own question, several notes that might be useful:
1. rename variable name into the format 'x[varid][instance][array]'
2. remove redundant columns if you are using merged outputs from multiple .tab files, such as f.eid_x, f.eid_y (just keep one of them)

**Comment by louise** [comment]
Thanks for your question, and answering it. Yes, the column name format should be exactly as stated in the documentation. 

Best wishes, Louise
