### ISSUE TITLE
Issue with resDir Argument in phenomeScan.r Script

### ISSUE THREAD

**Issue by senmingjiu** [MRCIEU/PHESANT#40]
Hello，
I am currently using the phenomeScan.r script from the PHESANT package and have encountered an issue with the --resDir argument. Despite providing this argument in my command, the script reports an error stating that the resDir argument must be supplied.

Here is the error message I receive:
Error: resDir argument must be supplied

And this is the command I'm using:
Rscript /Users/senmingjiu/Desktop/test/PWAS/PHESANT-master/WAS/phenomeScan.r
--phenofile="/Users/senmingjiu/Desktop/test/PWAS/ukbdata.csv"
--traitofinterestfile="/Users/senmingjiu/Desktop/test/PWAS/PRS.csv"
--variablelistfile="/Users/senmingjiu/Desktop/test/PWAS/PHESANT-master/variable-info/outcome-info.tsv"
--datacodingfile="/Users/senmingjiu/Desktop/test/PWAS/PHESANT-master/variable-info/data-coding-ordinal-info.txt"
--traitofinterest="PRS"
--resDir="/Users/senmingjiu/Desktop/test/PWAS/results"
--userId="eid"

I have checked and confirmed that the path provided for --resDir is correct and that the directory exists. Could you please advise on what might be causing this issue and how to resolve it? Is there a specific format or requirement for the --resDir argument that I might be missing?

Thank you for your assistance.

**Comment by louise** [comment]
Hi, it looks like you have a command that spans multiple lines, but without using the backslash at the end of each line to indicate as such. See for example here – https://github.com/MRCIEU/PHESANT
