### ISSUE TITLE
update the data-coding-ordinal-info.txt file

### ISSUE THREAD

**Issue by senmingjiu** [MRCIEU/PHESANT#42]
Hello，

How do I update the data-coding-ordinal-info.txt file after I have updated the outcome-info.tsv file and the coding in the data_code?

**Comment by louise** [comment]
Hi, I am not sure what you mean, please can you provide concrete details of your problem.
Best regards, Louise

**Comment by senmingjiu** [comment]
> Hi, I am not sure what you mean, please can you provide concrete details of your problem. Best regards, Louise

Thanks to your prompt response. 

I have utilized the script addNewFields.sh from the update-outcome-info file to update the outcome-info.tsv file, incorporating numerous modifications successfully. Additionally, I have updated the coding files under the PHESANT-master/ukb_data_codes/data_codes folder using the updated outcome-info-.tsv file.

However, I am currently facing a challenge with updating the data-coding-ordinal-info.txt file located in the PHESANT-master/variable-info/ folder. Despite my efforts, I have not yet found a method to apply the necessary updates to this file. Given that the outcome-info.tsv file now includes an additional 1524 field IDs, I wonder if updating the data-coding-ordinal-info.txt file is essential for the integrity of our project.

Could you please advise on whether the update of the data-coding-ordinal-info.txt file is necessary, and if so, suggest a potential method for accomplishing this task? Your expertise and insights would be greatly appreciated.
