### ISSUE TITLE
The url in the 'update-outcome-info' expired

### ISSUE THREAD

**Issue by Y-Isaac** [MRCIEU/PHESANT#46]
Hi, thanks for this useful tools! However, when I want to update the 'outcome-info.tsv' file as the tutorial mentioned, I found that the link to this code `wget http://biobank.ctsu.ox.ac.uk/%7Ebbdatan/Data_Dictionary_Showcase.csv` is no longer valid, there is any new solutions?

**Comment by louise** [comment]
Hi, unfortunately it seems UK Biobank are no longer providing a data dictionary. However, it should still be possible to add phenotypes to PHESANT manually, and if you would like me to look into this then please let me know what fields you would like added.
Best wishes, Louise
