### ISSUE TITLE
the full version of outcome-info.tsv and data-coding-ordinal-info.txt

### ISSUE THREAD

**Issue by jiehuang001** [MRCIEU/PHESANT#5]
Hi, there:

Two files are used in the example script and came with download package:
1. ../variable-info/outcome-info.tsv
2. ../variable-info/data-coding-ordinal-info.txt.

Where do I get the full version of these files, if I am processing my own UKB phenotype file, with thousands of traits, pretty much all the traits from UKB? 

Feel a bit frustrated that I still could not successfully run this from start to end, after I tried for more than a few months. I hope that someone could kindly help me out here.

Best regards,
Jie

**Comment by PhilPalmer** [comment]
Hi @jiehuang001,

Where you able to the full version of these files in the end?

Thanks in advance,
Phil

**Comment by jiehuang001** [comment]
Thanks Phil, for asking! I was not able to, and I had to quit on using PHESANT. I still hope that someone can give me more detailed instructions on making this tool work. After all, I felt that I almost spent one year to explore it.

 

Best regards,

Jie

 

 

发件人: PhilPalmer [mailto:notifications@github.com] 
发送时间: 2019年1月31日 0:01
收件人: MRCIEU/PHESANT <PHESANT@noreply.github.com>
抄送: jiehuang001 <jiehuang001@gmail.com>; Mention <mention@noreply.github.com>
主题: Re: [MRCIEU/PHESANT] the full version of outcome-info.tsv and data-coding-ordinal-info.txt (#5)

 

Hi @jiehuang001 <https://github.com/jiehuang001> ,

Where you able to the full version of these files in the end?

Thanks in advance,
Phil

**Comment by louise** [comment]
Dear Jie,

Apologies for the delayed reply. Are you the same Jie Huang I have been emailing?

The files included in PHESANT are the full versions - there may be some fields missing that have been added to UKB very recently. If you feel this is not the case (i.e. lots of fields are missing), then please provide some examples.

PHESANT is ready to run straight away, by following the instructions provided. If you are struggling to run the tool then please email me (louise.millard@bristol.ac.uk) with your code and output files, and I will help to resolve your issues. (as I said in my email if you are the same Jie Huang)

Best wishes,

Louise

**Comment by jiehuang001** [comment]
Dear Louise:

 

Yes, I am the same Jie Huang who have emailed you several times J

 

I will follow up with you again by email.

 

Best regards,

Jie

 

 

发件人: Louise [mailto:notifications@github.com] 
发送时间: 2019年1月31日 15:59
收件人: MRCIEU/PHESANT <PHESANT@noreply.github.com>
抄送: jiehuang001 <jiehuang001@gmail.com>; Mention <mention@noreply.github.com>
主题: Re: [MRCIEU/PHESANT] the full version of outcome-info.tsv and data-coding-ordinal-info.txt (#5)

 

Dear Jie,

Apologies for the delayed reply. Are you the same Jie Huang I have been emailing?

The files included in PHESANT are the full versions - there may be some fields missing that have been added to UKB very recently. If you feel this is not the case (i.e. lots of fields are missing), then please provide some examples.

PHESANT is ready to run straight away, by following the instructions provided. If you are struggling to run the tool then please email me (louise.millard@bristol.ac.uk <mailto:louise.millard@bristol.ac.uk> ) with your code and output files, and I will help to resolve your issues. (as I said in my email if you are the same Jie Huang)

Best wishes,

Louise

**Comment by xiaoxihe** [comment]
Hi！huangjie！I'm trying to run phesant using my own data, and then I almost want to quit also. How about your progess? Can I get your email to communicate with you? Thank you! 谢谢啦！给个邮箱！

**Comment by louise** [comment]
Hi xiaoxihe,

Please contact me on louise.millard@bristol.ac.uk if you would like some
help running PHESANT. Please be aware that PHESANT is a tool for use with
UK Biobank data only, so it is not setup for use with other data.

Best wishes,

Louise

**Comment by jiehuang001** [comment]
Hi, my email is jiehuang001@gmail.com <mailto:jiehuang001@gmail.com> . 

 

发件人: xiaoxihe [mailto:notifications@github.com] 
发送时间: 2019年4月9日 21:07
收件人: MRCIEU/PHESANT <PHESANT@noreply.github.com>
抄送: jiehuang001 <jiehuang001@gmail.com>; Mention <mention@noreply.github.com>
主题: Re: [MRCIEU/PHESANT] the full version of outcome-info.tsv and data-coding-ordinal-info.txt (#5)

 

Hi！huangjie！I'm trying to run phesant using my own data, and then I almost want to quit also. How about your progess? Can I get your email to communicate with you? Thank you! 谢谢啦！给个邮箱！
