### ISSUE TITLE
Getting error running the example

### ISSUE THREAD

**Issue by yang654** [MRCIEU/PHESANT#9]
Hi, 
Thanks for developing PHESANT which is a very useful tool. I was wondering if you could help me with the following issue.  Your help will be greatly appreciated!
When I ran the example,  it showed an error as follows:
[1] "Running with part 1 of 20  in phenotype file: "PHESANT-0.17/testWAS/data/phenotypes.csv"
[1] "Validating phenotype data ..."
[1] "Number of columns in phenotype file: 38"
Error: phenotype file doesn't contain required assessment centre colunn: x54_0_0
Execution halted
Here are my codes:
cd "/PHESANT-0.17/WAS/"
Rscript phenomeScan.r \
--phenofile="/PHESANT-0.17/testWAS/data/phenotypes.csv" \
--traitofinterestfile="//PHESANT-0.17/testWAS/data/exposure.csv" \
--variablelistfile="/variable-info/outcome-info.tsv" \
--datacodingfile="TPHESANT-0.17/variable-info/data-coding-ordinal-info.txt" \
--traitofinterest="exposure" \
--resDir="/PHESANT-0.17/results2/" \
--userId="userId" \
--sensitivity \
--genetic=FALSE \
--partIdx=1 \
--numParts=20

**Comment by louise** [comment]
Hi yang654, I have just tried the testWAS using the example command in the PHESANT testWAS README, and it runs fine. Please change your command to use relative rather than absolute paths (e.g. "../testWAS/data/phenotypes.csv"), so that I can try to reproduce the issue.

Best wishes, Louise

**Comment by yang654** [comment]
Dear Louise,
Thank you very much four reply. It runs fine  when  I do as you sugesst.  Many thanks for your help!



Best,
Hongxi







At 2019-04-10 04:11:47, "Louise" <notifications@github.com> wrote:


Hi yang654, I have just tried the testWAS using the example command in the PHESANT testWAS README, and it runs fine. Please change your command to use relative rather than absolute paths (e.g. "../testWAS/data/phenotypes.csv"), so that I can try to reproduce the issue.

Best wishes, Louise

**Comment by yang654** [comment]
Dear Louise,
I hope you're doing well. I tried the testWAS using the example command in the PHESANT_v0.17 , and it runs fine, however it didn't work in the PHESANT_v0.18. It shows the error: 
[1] "Running with all traits in phenotype file: home/PHESANT/PHESANT/testWAS/data/phenotypes.csv"
[1] "Validating phenotype data ..."
[1] "Number of columns in phenotype file: 1"
Error: phenotype file doesn't contain userID colunn: userId
Execution halted
When I used my own data which are also from UK Biobank, it shows the same error. My data file as follows:
phenotype file columns include :"userId","x31_0_0","x21022_0_0","x54_0_0","x54_1_0","x54_2_0","x93_0_0","x93_0_1","x93_1_0","x93_1_1","x93_2_0","x93_2_1","x94_0_0","x94_0_1","x94_1_0","x94_1_1","x94_2_0","x94_2_1","x95_0_0","x95_0_1","x95_1_0","x95_1_1","x95_2_0","x95_2_1","x102_0_0","x102_0_1","x102_1_0","x102_1_1","x102_2_0","x102_2_1","x23104_0_0","x23104_1_0","x40006_0_0","x40006_1_0","x40006_2_0","x40006_3_0","x40006_4_0","x40006_5_0","x40006_6_0","x40006_7_0","x40006_8_0","x40006_9_0","x40006_10_0","x40006_11_0","x40006_12_0","x40006_13_0","x40006_14_0","x40006_15_0","x40006_16_0","x40006_17_0","x40006_18_0","x40006_19_0","x40006_20_0","x40006_21_0","x40006_22_0","x40006_23_0","x40006_24_0","x40006_25_0","x40006_26_0","x40006_27_0","x40006_28_0","x40006_29_0","x40006_30_0","x40006_31_0"
traitofinterestfile colcums include "userId","exposure". 
I have also a  general question. When I run PHESANT using the phenotype file downloaded from UK Biobank,  is it right that all I just do is to change the column names into  PHESANT phenofile formats ? Your help will be greatly appreciated! Many thanks!

Kind Regards,

Hongxi

**Comment by louise** [comment]
Hi Hongxi,

Sorry for such a slow reply.

I hope you found answers already. If not, then:

RE your error, this is because of a new option allowing the phenotype data to have tab delimiters instead of commas. For a time tab was the default but I updated this so if you use the the latest release the default is commas so that should not be an issue now.

RE your question about formatting the phenotype data for PHESANT, yes that should be all you need to do.

Best wishes,

Louise
